"""add sent_in_group to messages

Revision ID: 9ada382a83cd
Revises: 89cbf38482e0
Create Date: 2026-09-14 20:02:40.547367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ada382a83cd'
down_revision: Union[str, Sequence[str], None] = '89cbf38482e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sent_in_group', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sent_in_group')
    # ### end Alembic commands ###
